version: '3'

services: 
  app:
    image: express-clm-demo:latest
    build: .
    env_file: .env
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 120
