version: '3'

services: 
  app:
    image: express-clm-demo:latest
    build: .
    env_file: .env
    command: npm run start
    ports:
      - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
 elasticsearch-data:
  driver: local
